# Generated by Django 2.2.3 on 2019-07-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='image',
        ),
        migrations.AddField(
            model_name='login',
            name='nome',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
